version = 2
half = true

[train_data]
dataset = "CIFAR10"
train = true
batch_size = 128
shuffle = true
normalize = [[0.4914, 0.4822, 0.4465], [0.2023, 0.1994, 0.2010]]
transform = [
  ["RandomHorizontalFlip" ],
  ["RandomCrop", { size=[32,32], padding=4, padding_mode="reflect", resample="NEAREST" }]
]

[test_data]
dataset = "CIFAR10"
batch_size = 500
end = 5000
normalize = [[0.4914, 0.4822, 0.4465], [0.2023, 0.1994, 0.2010]]

[valid_data]
dataset = "CIFAR10"
start = 5000
batch_size = 500
normalize = [[0.4914, 0.4822, 0.4465], [0.2023, 0.1994, 0.2010]]

[model]
block1 = [
  ["Conv2d", "$nfeat", {kernel_size=3, padding="same", bias=false} ],
  ["BatchNorm2d", {momentum=0.05} ],
  ["ReLU"], 
  ["Dropout", 0.2],
]

block2 = [
  ["Conv2d", "$nfeat", {kernel_size=3, padding="same", bias=false} ],
  ["BatchNorm2d", {momentum=0.05} ],
  ["ReLU"],
  ["MaxPool2d", 2 ],
  ["Dropout", 0.2 ],
]

layers = [
  ["block1", {nfeat=64} ],
  ["block1", {nfeat=128} ],
  ["block1", {nfeat=128} ],
  ["block2", {nfeat=128} ],
  ["block1", {nfeat=128} ],
  ["block1", {nfeat=128} ],
  ["block2", {nfeat=256} ],
  ["block1", {nfeat=256} ],
  ["block2", {nfeat=256} ],
  ["block1", {nfeat=512} ],
  
  ["Conv2d", {out_channels=2048, kernel_size=1, padding="same"} ],
  ["ReLU"],
  ["Dropout", 0.2],

  ["Conv2d", {out_channels=256, kernel_size=1, padding="same"} ],
  ["ReLU"],
  ["MaxPool2d", 2 ],
  ["Dropout", 0.2],

  ["Conv2d", {out_channels=256, kernel_size=3, padding="same"} ],
  ["ReLU"],
  ["MaxPool2d", 2 ],

  ["Flatten"],
  ["Linear", 10 ],
]

[weight_init]
Linear = ["xavier_uniform"]
Conv2d = ["xavier_uniform"]

[train]
optimizer = ["SGD", {lr=0.02, momentum=0.9, nesterov=true, weight_decay=2e-5} ]
scheduler = ["ReduceLROnPlateau", "valid_loss", {factor=0.2, verbose=true} ]
stop = {epochs=3, extra=5, avg=20}
epochs = 150

