half = true

[train_data]
dataset = "CIFAR10"
train = true
batch_size = 128
normalize = [[0.4914, 0.4822, 0.4465], [0.2023, 0.1994, 0.2010]]

[test_data]
dataset = "CIFAR10"
batch_size = 500
end = 5000
normalize = [[0.4914, 0.4822, 0.4465], [0.2023, 0.1994, 0.2010]]

[valid_data]
dataset = "CIFAR10"
start = 5000
batch_size = 500
normalize = [[0.4914, 0.4822, 0.4465], [0.2023, 0.1994, 0.2010]]

[model]
conv = [
  ["Conv2d", {out_channels="$nfeat", kernel_size=3, padding=1} ],
  ["BatchNorm2d"],
  ["ReLU", {inplace=true} ],
]

layers = [
  ["conv", {nfeat=64} ],
  ["conv", {nfeat=64} ],
  ["MaxPool2d", {kernel_size=2, stride=2}],
  ["conv", {nfeat=128} ],
  ["conv", {nfeat=128} ],
  ["MaxPool2d", {kernel_size=2, stride=2}],
  ["conv", {nfeat=256} ],
  ["conv", {nfeat=256} ],
  ["conv", {nfeat=256} ],
  ["MaxPool2d", {kernel_size=2, stride=2}],
  ["conv", {nfeat=512} ],
  ["conv", {nfeat=512} ],
  ["conv", {nfeat=512} ],
  ["MaxPool2d", {kernel_size=2, stride=2}],
  ["conv", {nfeat=512} ],
  ["conv", {nfeat=512} ],
  ["conv", {nfeat=512} ],
  ["MaxPool2d", {kernel_size=2, stride=2}],
  ["AvgPool2d", {kernel_size=1, stride=1}],
  ["Flatten"],
  ["Linear", 10 ],
]

[transform]
transforms = [
  ["RandomHorizontalFlip"],
  ["RandomCrop", { size=[32,32], padding=4, padding_mode="reflect", resample="NEAREST" }]
]

[train]
optimizer = ["Adam", {lr=0.001, weight_decay=5e-4} ]
scheduler = ["StepLRandWeightDecay", {step_size=15, gamma=0.3} ]
stop = {epochs=2, extra=4, avg=12}
epochs = 80
shuffle = true

