[train_data]
dataset = "CIFAR10"
train = true
batch_size = 256
shuffle = true
transform = [
  ["RandomHorizontalFlip"],
  ["RandomCrop", { size=[32,32], padding=4, padding_mode="reflect", resample="NEAREST" }],
  ["Normalize", [0.4914, 0.4822, 0.4465], [0.2023, 0.1994, 0.2010]]
]
multi_process = true

[test_data]
dataset = "CIFAR10"
batch_size = 1000
transform = [
  ["Normalize", [0.4914, 0.4822, 0.4465], [0.2023, 0.1994, 0.2010]]
]

[model]
layers = [
  ["Conv2d", 32, {kernel_size=3, padding="same"} ],
  ["ReLU"],
  ["Conv2d", 32, {kernel_size=3} ],
  ["ReLU"],
  ["MaxPool2d", 2 ],
  ["Dropout", 0.25 ],
  ["Conv2d", 64, {kernel_size=3, padding="same"} ],
  ["ReLU"],
  ["Conv2d", 64, {kernel_size=3} ],
  ["ReLU"],
  ["MaxPool2d", 2 ],
  ["Dropout", 0.25 ],
  ["Flatten"],
  ["Linear", 512 ],
  ["ReLU"],
  ["Dropout", 0.5 ],
  ["Linear", 10 ],
]

[train]
optimizer = ["Adam", {lr = 0.0005 }]
epochs = 50


