version = 1
half = true

[train_data]
dataset = "Imagenet"
train = true
batch_size = 128
shuffle = true
resize = 232
transform = [
  ["RandomCrop", [224, 224]],
  ["RandomHorizontalFlip"],
  ["Normalize", [0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]
]
multi_process = true

[test_data]
dataset = "Imagenet"
batch_size = 200
resize = 232
transform = [
  ["CenterCrop", 224],
  ["Normalize", [0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]
]

[model]
block = [
  ["Conv2d", "$expand", 1, {bias=false}],
  ["BatchNorm2d"],
  ["ReLU", {inplace=true}],
  ["Conv2d", "$expand", 3, {stride="$stride", padding=1, groups="$expand", bias=false}],
  ["BatchNorm2d"],
  ["ReLU", {inplace=true}],
  ["Conv2d", "$nout", 1, {bias=false}],
  ["BatchNorm2d"],
]

shortcut = [
  ["Conv2d", "$nout", 1, {stride=1, bias=false}],
  ["BatchNorm2d"],
]

empty = []

block1 = [
  ["AddBlock", "block", "shortcut", {nout="$nout", expand="$expand", stride="$stride"}],
]

block2 = [
  ["AddBlock", "block", "empty", {nout="$nout", expand="$expand", stride="$stride"}],
]

layers = [
  ["Conv2d", 32, 3, {stride=2, padding=1, bias=false}],
  ["BatchNorm2d"],
  ["ReLU", {inplace=true}],

  ["block1", {nout=16, expand=32, stride=1}],

  ["block",  {nout=24, expand=96, stride=2}],
  ["block2", {nout=24, expand=144, stride=1}],

  ["block",  {nout=32, expand=144, stride=2}],
  ["block2", {nout=32, expand=192, stride=1}],
  ["block2", {nout=32, expand=192, stride=1}],

  ["block",  {nout=64, expand=192, stride=2}],
  ["block2", {nout=64, expand=384, stride=1}],
  ["block2", {nout=64, expand=384, stride=1}],
  ["block2", {nout=64, expand=384, stride=1}],

  ["block1", {nout=96, expand=384, stride=1}],
  ["block2", {nout=96, expand=576, stride=1}],
  ["block2", {nout=96, expand=576, stride=1}],

  ["block",  {nout=160, expand=576, stride=2}],
  ["block2", {nout=160, expand=960, stride=1}],
  ["block2", {nout=160, expand=960, stride=1}],

  ["block1",  {nout=320, expand=960, stride=1}],

  ["Conv2d", 1280, 1, {bias=false}],
  ["BatchNorm2d"],
  ["ReLU", {inplace=true}],

  ["AvgPool2d", 7],
  ["Flatten"],
  ["Dropout", 0.2],
  ["Linear", 1000],
]

[weight_init]
Linear = ["normal", {std=0.01}]
Conv2d = ["kaiming_normal", {mode="fan_out", nonlinearity="relu"}]

[train]
optimizer = ["SGD", {lr=0.075, momentum=0.9, nesterov=true, weight_decay=4e-5} ]
scheduler = ["ExponentialLR", {gamma=0.98} ]
epochs = 200
