version = 2

[train_data]
dataset = "MNIST"
train = true
end = 50000
batch_size = 256
shuffle = true
normalize = [[0.1307], [0.3081]]
transform = [
  ["RandomAffine", { p=0.5, degrees=15, scale=[0.85,1.15], padding_mode="reflection" }],
  ["RandomElasticTransform", { p=0.5, kernel_size=[9,9], sigma=[4.0,4.0], alpha=[0.5,0.5], padding_mode="reflection" }],
]

[valid_data]
dataset = "MNIST"
train = true
start = 50000
batch_size = 1000
normalize = [[0.1307], [0.3081]]

[test_data]
dataset = "MNIST"
batch_size = 1000
normalize = [[0.1307], [0.3081]]

[model]
layers = [
  ["Conv2d", 32, {kernel_size=5} ],
  ["MaxPool2d", 2 ],
  ["Conv2d", 64, {kernel_size=5} ],
  ["MaxPool2d", 2 ],
  ["Flatten"],
  ["Linear", 1024 ],
  ["ReLU"],
  ["Dropout", 0.5 ],
  ["Linear", 10 ],
]

[train]
optimizer = ["Adam", {lr = 0.002} ]
scheduler = ["StepLR", {step_size=15, gamma=0.2} ]
epochs = 60
stop = {epochs=2, avg=10, extra=2}
